/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dedrick Koh (https://sketchfab.com/koribakusuta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-room-bb58f5e45c344990b805eec22f37dcb3
Title: Sci Fi Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sci_fi_room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Objects1_lambert2_0.geometry}
        material={materials.lambert2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EverythingElse1_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  )
}

useGLTF.preload('/sci_fi_room.glb')
